// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7TztuV9lOq1089jKduk8wGa5-bL4UuU',
    appId: '1:238336819139:android:580f22982d57b3374f4776',
    messagingSenderId: '238336819139',
    projectId: 'together-wellness',
    storageBucket: 'together-wellness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1wzT3D5BpYhq0PGDZ1SSWBzFweyhD1w',
    appId: '1:238336819139:ios:626243ea03a75b044f4776',
    messagingSenderId: '238336819139',
    projectId: 'together-wellness',
    storageBucket: 'together-wellness.firebasestorage.app',
    androidClientId: '238336819139-4vcu9uoltpv01cudbrm00c5beccseup1.apps.googleusercontent.com',
    iosClientId: '238336819139-9pbtd4lp724dh43u7ebp7f21hos7ntq4.apps.googleusercontent.com',
    iosBundleId: 'com.velmorarelatioship',
  );

}